### ISSUE TITLE
Tracking issue String only compat

### ISSUE THREAD

**Issue by timbru31** [timbru31/SilkSpawners#149]
- [x] - newEggItem - do old methods accept, Wiki states 1.9+ are able to use EntityTags.
- [x] - spawnEntity - old methods want a numerical value, are newer ones able to use e.g. MinecraftKey?
- [x] - look through missing `@Nullable` annotations
- [x] - searchItemMeta needs to handle legacy number values
- [x] - crafting results in wrong entity spawners
- [x] - command alias are not displayed
- [x] - prevent duplicate alias keys
- [x] - fallback for IRON_FENCE (now IRON_BARS) in default crafting
- [x] - add 1.13 mobs to default config
- [x] - bring back ignoreCheckNumbers (useful for older versions)
- [x] - test with mods (e.g. MoCreatures)
- [x] - remove ID from boss bar (obsolete)

**Comment by timbru31** [comment]
[ ] - chanegtype permissions might be broken
